# defaults
motor_pd:
  j_arm*_1: [500, 10]
  j_arm*_2: [500, 10]
  j_arm*_3: [500, 10]
  j_arm*_4: [500, 10]
  j_arm*_5: [100, 5]
  j_arm*_6: [100, 5]
  j_arm*_7: [100, 5]
  hip_yaw_*: [3000, 30]
  hip_pitch_*: [3000, 30]
  knee_pitch_*: [3000, 30]
  ankle_pitch_*: [1000, 10]
  ankle_yaw_*: [300, 10]
  neck_pitch: [10, 1]
  neck_yaw: [10, 1]
  torso_yaw: [1000, 30]
  j_wheel_*: [0, 30]
  velodyne_*: [10, 1]
  d435_*: [10, 1]

# startup pd config
# startup_motor_pd:
#   j_arm*_1: [500, 10]
#   j_arm*_2: [500, 10]
#   j_arm*_3: [500, 10]
#   j_arm*_4: [500, 10]
#   j_arm*_5: [100, 5]
#   j_arm*_6: [100, 5]
#   j_arm*_7: [100, 5]
#   hip_yaw_*: [3000, 30]
#   hip_pitch_*: [3000, 30]
#   knee_pitch_*: [3000, 30]
#   ankle_pitch_*: [1000, 10]
#   ankle_yaw_*: [300, 10]
#   neck_pitch: [10, 1]
#   neck_yaw: [10, 1]
#   torso_yaw: [1000, 30]
#   j_wheel_*: [0, 30]
#   velodyne_*: [10, 1]
#   d435_*: [10, 1]

# startup_motor_pd: # iannis combo
#   j_arm*_1: [500, 30]
#   j_arm*_2: [500, 30]
#   j_arm*_3: [500, 30]
#   j_arm*_4: [500, 30]
#   j_arm*_5: [100, 5]
#   j_arm*_6: [100, 5]
#   j_arm*_7: [100, 5]
#   hip_yaw_*: [200, 60]
#   hip_pitch_*: [200, 60]
#   knee_pitch_*: [200, 60]
#   ankle_pitch_*: [200, 60]
#   ankle_yaw_*: [120, 30]
#   neck_pitch: [10, 1]
#   neck_yaw: [10, 1]
#   torso_yaw: [1000, 30]
#   j_wheel_*: [0, 30]
#   velodyne_*: [10, 1]
#   d435_*: [10, 1]

startup_motor_pd: # iannis combo
  j_arm*_1: [500, 30]
  j_arm*_2: [500, 30]
  j_arm*_3: [500, 30]
  j_arm*_4: [500, 30]
  j_arm*_5: [100, 5]
  j_arm*_6: [100, 5]
  j_arm*_7: [100, 5]
  hip_yaw_*: [400, 60]
  hip_pitch_*: [400, 60]
  knee_pitch_*: [400, 60]
  ankle_pitch_*: [400, 60]
  ankle_yaw_*: [240, 50]
  neck_pitch: [10, 1]
  neck_yaw: [10, 1]
  torso_yaw: [1000, 30]
  j_wheel_*: [0, 30]
  velodyne_*: [10, 1]
  d435_*: [10, 1]

# open
# startup_motor_pd:
#   j_arm*_1: [500, 30]
#   j_arm*_2: [500, 30]
#   j_arm*_3: [500, 30]
#   j_arm*_4: [500, 30]
#   j_arm*_5: [100, 5]
#   j_arm*_6: [100, 5]
#   j_arm*_7: [100, 5]
#   hip_yaw_*: [800, 80]
#   hip_pitch_*: [800, 80]
#   knee_pitch_*: [800, 80]
#   ankle_pitch_*: [800, 80]
#   ankle_yaw_*: [480, 50]
#   neck_pitch: [10, 1]
#   neck_yaw: [10, 1]
#   torso_yaw: [1000, 30]
#   j_wheel_*: [0, 30]
#   velodyne_*: [10, 1]
#   d435_*: [10, 1]

# startup_motor_pd: # open loop
#   j_arm*_1: [500, 10]
#   j_arm*_2: [500, 10]
#   j_arm*_3: [500, 10]
#   j_arm*_4: [500, 10]
#   j_arm*_5: [100, 5]
#   j_arm*_6: [100, 5]
#   j_arm*_7: [100, 5]
#   hip_yaw_*: [800, 60]
#   hip_pitch_*: [800, 60]
#   knee_pitch_*: [800, 60]
#   ankle_pitch_*: [800, 60]
#   ankle_yaw_*: [240, 60]
#   neck_pitch: [10, 1]
#   neck_yaw: [10, 1]
#   torso_yaw: [1000, 30]
#   j_wheel_*: [0, 30]
#   velodyne_*: [10, 1]
#   d435_*: [10, 1]

# startup_motor_pd: # more aggressive iannis combo
#   j_arm*_1: [500, 30]
#   j_arm*_2: [500, 30]
#   j_arm*_3: [500, 30]
#   j_arm*_4: [500, 30]
#   j_arm*_5: [100, 5]
#   j_arm*_6: [100, 5]
#   j_arm*_7: [100, 5]
#   hip_yaw_*: [600, 60]
#   hip_pitch_*: [600, 60]
#   knee_pitch_*: [600, 60]
#   ankle_pitch_*: [600, 60]
#   ankle_yaw_*: [300, 30]
#   neck_pitch: [10, 1]
#   neck_yaw: [10, 1]
#   torso_yaw: [1000, 30]
#   j_wheel_*: [0, 30]
#   velodyne_*: [10, 1]
#   d435_*: [10, 1]

# startup_motor_pd:
#   j_arm*_1: [500, 10]
#   j_arm*_2: [500, 10]
#   j_arm*_3: [500, 10]
#   j_arm*_4: [500, 10]
#   j_arm*_5: [100, 5]
#   j_arm*_6: [100, 5]
#   j_arm*_7: [100, 5]
#   hip_yaw_*: [800, 10]
#   hip_pitch_*: [800, 10]
#   knee_pitch_*: [800, 10]
#   ankle_pitch_*: [800, 10]
#   ankle_yaw_*: [200, 10]
#   neck_pitch: [10, 1]
#   neck_yaw: [10, 1]
#   torso_yaw: [800, 30]
#   j_wheel_*: [0, 30]
#   velodyne_*: [10, 1]
#   d435_*: [10, 1]

# startup_motor_pd:
#   j_arm*_1: [500, 10]
#   j_arm*_2: [500, 10]
#   j_arm*_3: [500, 10]
#   j_arm*_4: [500, 10]
#   j_arm*_5: [100, 5]
#   j_arm*_6: [100, 5]
#   j_arm*_7: [100, 5]
#   hip_yaw_*: [250, 5]
#   hip_pitch_*: [250, 5]
#   knee_pitch_*: [250, 5]
#   ankle_pitch_*: [250, 5]
#   ankle_yaw_*: [200, 5]
#   neck_pitch: [10, 1]
#   neck_yaw: [10, 1]
#   torso_yaw: [500, 30]
#   j_wheel_*: [0, 30]
#   velodyne_*: [10, 1]
#   d435_*: [10, 1]

# startup_motor_pd:
#   j_arm*_1: [500, 10]
#   j_arm*_2: [500, 10]
#   j_arm*_3: [500, 10]
#   j_arm*_4: [500, 10]
#   j_arm*_5: [100, 5]
#   j_arm*_6: [100, 5]
#   j_arm*_7: [100, 5]
#   hip_yaw_*: [100, 5]
#   hip_pitch_*: [100, 5]
#   knee_pitch_*: [100, 5]
#   ankle_pitch_*: [100, 5]
#   ankle_yaw_*: [50, 5]
#   neck_pitch: [10, 1]
#   neck_yaw: [10, 1]
#   torso_yaw: [500, 30]
#   j_wheel_*: [0, 30]
#   velodyne_*: [10, 1]
#   d435_*: [10, 1]